# Generated by Django 3.0.4 on 2020-03-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('faq_checkd', models.BooleanField(default=False)),
                ('answer_text', models.CharField(max_length=1000, null=True)),
                ('answer_related_post', models.CharField(max_length=100, null=True)),
                ('answer_time', models.DateTimeField(null=True)),
                ('was_helpfull', models.IntegerField(choices=[(0, 'Not Answered'), (1, 'Helpfull'), (2, 'Not Helpfull')])),
                ('related_faq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.FAQ')),
            ],
        ),
    ]
