# Generated by Django 3.0.4 on 2020-03-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='was_helpfull',
            field=models.IntegerField(choices=[(0, 'Not Answered'), (1, 'Helpfull'), (2, 'Not Helpfull')], default=0),
        ),
    ]
