# Generated by Django 3.0.4 on 2020-03-30 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200329_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='faq_checkd',
            new_name='faq_checked',
        ),
    ]
