# Generated by Django 3.0.4 on 2020-04-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200330_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_related_post',
            new_name='answer_related_post_id',
        ),
        migrations.AddField(
            model_name='faq',
            name='fid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
