# Generated by Django 3.0.4 on 2020-04-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200402_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=100, null=True)),
                ('expiration_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='faq',
            name='fid',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
