# Generated by Django 3.0.4 on 2020-04-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200404_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
